# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: MASTERMANUAL
    url: https://mastermanual.mx/
  - name: UPA
    url: https://upa.edu.mx/
  - name: VIDEOTECA
    url: https://videotec.americansoftwoodsmexico.com/
  - name: IEEC
    url: https://ieec.mx/
  - name: MEGAWATT
    url: https://megawatt.com.mx/
  - name: PUNTORECARGA
    url: https://puntoderecarga.mx/
  - name: CANVAS IEEC
    url: https://canvas.ieec.mx/
  - name: CN CENTER
    url: https://causanaturacenter.org/
  - name: CN MEDIA
    url: https://causanaturamedia.com/
  - name: CN DONACIONES
    url: https://donaciones.causanatura.org/en

status-website:
  baseUrl: /Monitor # where "repo" is your repository name
  name: Monitor Designa

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
